"""The skill's vocabulary reference, rendered from the grammar.

`SKILL.md` used to restate all of this in hand-written tables — a third copy of
the vocabulary, and it had already drifted: it named one required file for a
research program where the grammar named two. Generating it means the skill
cannot disagree with the engine, and `tests/test_reference.py` fails if the
committed file falls behind.

Only the grammar goes in here. What a *particular* tree actually contains is
the snapshot's job — putting it here would make a committed file depend on
one machine's private docs.
"""

from __future__ import annotations

from orglens.grammar import Grammar

BANNER = "<!-- generated by `orglens reference` — do not edit -->"


def render(grammar: Grammar) -> str:
    lines = [
        BANNER,
        "",
        "# Vocabulary",
        "",
        "This tree's grammar, rendered. It says what may exist and what each part",
        "is for. It does **not** say what is there — run `orglens snapshot` for that,",
        "and read the snapshot rather than scanning directories.",
        "",
        "## Where anything stands",
        "",
        f"Every entity carries **`{grammar.driver}`** — one document, same name for every",
        "kind, saying where that entity stands and what is next. It is the first thing",
        "to read and the first place a status line is looked for.",
        "",
        "Long documents it refers to stay separate and are pointed at from it, so it",
        "can be read in a screen.",
        "",
        "## What exists",
        "",
        "Patterns are relative: matched at the docs root, then inside every entity",
        "found. Nesting is never declared, so anything can contain anything.",
        "",
        "| Kind | Found at |",
        "|------|----------|",
    ]
    for name, entity_type in grammar.entity_types.items():
        lines.append(f"| `{name}` | `{entity_type.pattern}` |")

    lines += [
        "",
        "A directory that matches **is** one of these, whether or not it holds the",
        "files below. Nothing is hidden for being incomplete; `orglens check`",
        "reports the gap and changes nothing.",
        "",
        "## Documents",
        "",
        "| Kind | Found at | What it is |",
        "|------|----------|------------|",
    ]
    for name, artifact_type in grammar.artifact_types.items():
        lines.append(
            f"| `{name}` | `{artifact_type.find}` | {artifact_type.means} |"
        )

    lines += [
        "",
        "Names are a convention, not a rule the engine enforces — nothing parses a",
        "filename. Follow the description; every file in the directory is found",
        "either way.",
        "",
        "## What each part is for",
        "",
    ]
    for name, entity_type in grammar.entity_types.items():
        lines += [
            f"### {name} — `{entity_type.pattern}`",
            "",
            "| Path | What it is for |",
            "|------|----------------|",
        ]
        for path, means in entity_type.structure.items():
            lines.append(f"| `{path}` | {means} |")
        lines.append("")

    lines += [
        "Created by `orglens new`, and consulted when you are deciding where a new",
        "document belongs. An entity commonly grows directories that appear nowhere",
        "above; those are real and the snapshot lists them.",
        "",
    ]
    return "\n".join(lines)
