"""A unit's homes, rendered into the config scad wants for a container.

The `repos:` block *is* a unit's homes with machine paths attached, which is
why it should not be maintained twice. This is the container lane only —
launching on this machine needs no config at all, because every home is
already on disk.

Generated, never hand-edited. Regenerate it instead; a file that is sometimes
authored and sometimes rendered drifts in the direction nobody notices.

The `runtime` block is passed through verbatim rather than modelled. Inventing
an orglens vocabulary for Python versions and plugins would be a translation
layer with exactly one consumer; carrying scad's words and saying so is
honest, and a vocabulary earns itself when a second runtime exists.
"""

from __future__ import annotations

import yaml

from orglens.units import Unit

BANNER = "# generated by `orglens config` — do not edit; regenerate instead"


def render(unit: Unit, workdir: str | None = None) -> str:
    """The scad config for this unit. Homes absent from this machine are left out.

    Two homes can name the same repository — a home at its root and another
    inside a subpath of it — so the repos block is keyed by the repository
    segment (`home.name.split("/")[0]`), and the first home to claim a key
    wins. Silently overwriting one mount with another would lose it without
    saying so.
    """
    present = [h for h in unit.homes if h.path is not None]

    repos: dict[str, dict] = {}
    for home in present:
        # Only the repository segment names a repo; a subpath inside one is
        # still that repository as far as a mount is concerned.
        key = home.name.split("/")[0]
        if key in repos:
            continue
        repos[key] = {"path": str(home.path)}

    # Marked after the loop, on the repo key — not the home name, which for
    # a subpath home is a different string and would mark nothing.
    chosen = workdir or next(iter(repos), None)
    if chosen in repos:
        repos[chosen]["workdir"] = True

    # Generated keys win: a `runtime:` block that happened to carry `name` or
    # `repos` must not clobber what render just built, or a declaration edit
    # would silently destroy the mounts — a config that fails inside the
    # container instead of before it.
    body: dict[str, object] = {"name": unit.name, "repos": repos}
    body.update({k: v for k, v in (unit.runtime or {}).items() if k not in body})

    return BANNER + "\n" + yaml.safe_dump(body, sort_keys=False)
